### ISSUE TITLE
Sidebar (tracker)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/search-a-licious#140]
### What

```[tasklist]
### Sidebar
- [ ] Sidebar
- [ ] Sidebar clickability
- [ ] Sidebar translations
- [ ] Use icons from the mockup for filters (also used in the app, in edit mode)
- [ ] Interactive Filtering for long-tail fields (eg: brands)
- [ ] interaction with search fields
```

### Part of
- #62
