### ISSUE TITLE
Create a documentation about search-a-licious and how to use it

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/search-a-licious#177]
```[tasklist]
### Tasks
- [ ] https://github.com/openfoodfacts/search-a-licious/issues/217
- [x] Documentation on the configuration file
- [x] Introduction to the API
- [x] Explanation on the taxonomies
- [x] Explanation on the components and how they are used
```

**Comment by alexgarel** [comment]
We are at a good point on dev front so we can close this.
