### ISSUE TITLE
Publish user documentation

### ISSUE THREAD

**Issue by alexgarel** [openfoodfacts/search-a-licious#184]
```[tasklist]
### Tasks
- [x] use mkdocs and material theme
- [x] Use sphinx to create the API documentation in a specific folder
- [x] Use [autodoc-pydantic](https://autodoc-pydantic.readthedocs.io/en/stable/index.html) with Sphinx to auto-generate configuration documentation
- [x] Eventually generate OpenAPI documentation to have it published standalone (with redoc or rapidoc)
- [x] Add a check in CI for documentation build
- [x] Publish all docs to github pages
- [ ] https://github.com/openfoodfacts/search-a-licious/issues/216
```

See other projects to re-use scripts that do that:
- [off-server generate doc](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/.github/workflows/generate-doc.yml)
- [off-server build_mkdocs](https://github.com/openfoodfacts/openfoodfacts-server/blob/main/scripts/build_mkdocs.sh)

**Comment by alexgarel** [comment]
@Kout95 this is a thing to do also.

I can take care of mkdocs part, because I did it a lot of times. 

But if you are ok to handle the sphinx build, I would be glad :-)
The most important part is to generate the documentation for the configuration because it enables centralizing precise documentation there.

**Comment by alexgarel** [comment]
Most is done.
